package webDownload;

import java.net.URL;

public class ConstVal {
	public static final String WEBB_URL_CCASS = "https://webb-site.com/ccass";
	public static final String WEBB_URL_BY_STOCK = "https://webb-site.com/ccass/choldings.asp?";
	
	public static final String FILE_OUTPUT_PATH = "D:\\stock data\\HK CCASS - WEBB SITE";
	
	public static final String WEBB_URL_SOUTHBOUND_SH = "https://webb-site.com/ccass/cholder.asp?part=1323";
	public static final String WEBB_URL_SOUTHBOUND_SZ = "https://webb-site.com/ccass/cholder.asp?part=1456";

	public static final String[] CGI_BLACKLIST_BROKERS = {"CHINA INDUSTRIAL SECURITIES","MASON SECURITIES LTD"
			,"EMPEROR SECURITIES LTD","GUOTAI JUNAN SECURITIES (HONG KONG) LTD","GET NICE SECURITIES LTD"
			,"ESSENCE INTERNATIONAL SECURITIES","GF SECURITIES (HONG KONG) BROKERAGE LTD","CONVOY INVESTMENT SERVICES LTD"
			,"HUARONG INTERNATIONAL SECURITIES LTD","QUAM SECURITIES CO LTD","	YUANTA SECURITIES (HONG KONG) CO LTD"
			,"GUOYUAN SECURITIES BROKERAGE (HONG KONG)","ENLIGHTEN SECURITIES LTD","CHINA GOLDJOY SECURITIES LTD"
			,"GUOSEN SECURITIES (HK) BROKERAGE CO LTD","KINGSTON SECURITIES LTD","ZHONGTAI INTERNATIONAL SECURITIES LTD"
			,"CENTRAL CHINA INTERNATIONAL SECURITIES","CAITONG INTERNATIONAL SECURITIES CO LTD","JUN YANG SECURITIES CO LTD"
			,"KOALA SECURITIES LTD","ORIENT SECURITIES (HONG KONG) LTD","BLACK MARBLE SECURITIES LTD"};
	public static final String CGI_NAME = "CHINA GALAXY INTERNATIONAL SECURITIES";
}
